blank_issues_enabled: false
contact_links:
  - name: üí¨ –û–±—Å—É–∂–¥–µ–Ω–∏—è
    url: https://github.com/FozerG/WinYandexMusicRPC/discussions
    about: –î–ª—è –≤–æ–ø—Ä–æ—Å–æ–≤ –∏ –æ–±—Å—É–∂–¥–µ–Ω–∏–π –∏—Å–ø–æ–ª—å–∑—É–π—Ç–µ —Ä–∞–∑–¥–µ–ª Discussions
